title: <p align="center"> Krishna Chaitanya Bh </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="http://linkedin.com/in/krishna-chaitanya-bh">LinkedIn</a> |
  <a href="https://github.com/Chaitu7">GitHub</a>
  <br>   
  I'm working as a Data Engineer. Have a proven track record of designing and implementing complex data solutions. Skilled in developing scalable ETL pipelines, data modeling, and deploying machine learning models.
  <br>
  </p>
theme: jekyll-theme-minimal
